import type { Metadata } from "next";
import "./globals.css";
import HeaderComponent from "@/components/Header.component";
import { Provider } from "@/components/ui/provider"


export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: Readonly<{ children: React.ReactNode }>) {
	return (
		<html lang="en">
			<body className="bg-[#f2f5fa] duration-300">
				<Provider>
					{children}
				</Provider>
			</body>
		</html>
	);
}
